/**
 * Cloudflare Worker entry point -- auto-generated by vinext deploy.
 * Edit freely or delete to regenerate on next deploy.
 */
import { handleImageOptimization, DEFAULT_DEVICE_SIZES, DEFAULT_IMAGE_SIZES } from "vinext/server/image-optimization";
import {
  matchRedirect,
  matchRewrite,
  matchHeaders,
  requestContextFromRequest,
  isExternalUrl,
  proxyExternalRequest,
} from "vinext/config/config-matchers";

import { renderPage, handleApiRoute, runMiddleware, vinextConfig } from "../dist/server/entry.js";

interface Env {
  ASSETS: {
    fetch(input: RequestInfo | URL, init?: RequestInit): Promise<Response>;
  };
  IMAGES: {
    input(stream: ReadableStream): {
      transform(options: Record<string, unknown>): {
        output(options: { format: string; quality: number }): Promise<{ response(): Response }>;
      };
    };
  };
}

// Extract config values (embedded at build time in the server entry)
const basePath: string = vinextConfig?.basePath ?? "";
const trailingSlash: boolean = vinextConfig?.trailingSlash ?? false;
const configRedirects = vinextConfig?.redirects ?? [];
const configRewrites = vinextConfig?.rewrites ?? { beforeFiles: [], afterFiles: [], fallback: [] };
const configHeaders = vinextConfig?.headers ?? [];

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    try {
      const url = new URL(request.url);
      let pathname = url.pathname;
      let urlWithQuery = pathname + url.search;

      // Block protocol-relative URL open redirects (//evil.com/ or /\evil.com/).
      // Normalize backslashes: browsers treat /\ as // in URL context.
      const safePath = pathname.replace(/\\/g, "/");
      if (safePath.startsWith("//")) {
        return new Response("404 Not Found", { status: 404 });
      }

      // ── 1. Strip basePath ─────────────────────────────────────────
      if (basePath && pathname.startsWith(basePath)) {
        const stripped = pathname.slice(basePath.length) || "/";
        urlWithQuery = stripped + url.search;
        pathname = stripped;
      }

      // ── Image optimization via Cloudflare Images binding ──────────
      // Checked after basePath stripping so /<basePath>/_vinext/image works.
      if (pathname === "/_vinext/image") {
        const allowedWidths = [...DEFAULT_DEVICE_SIZES, ...DEFAULT_IMAGE_SIZES];
        return handleImageOptimization(request, {
          fetchAsset: (path) => env.ASSETS.fetch(new Request(new URL(path, request.url))),
          transformImage: async (body, { width, format, quality }) => {
            const result = await env.IMAGES.input(body).transform(width > 0 ? { width } : {}).output({ format, quality });
            return result.response();
          },
        }, allowedWidths);
      }

      // ── 2. Trailing slash normalization ────────────────────────────
      if (pathname !== "/" && !pathname.startsWith("/api")) {
        const hasTrailing = pathname.endsWith("/");
        if (trailingSlash && !hasTrailing) {
          return new Response(null, {
            status: 308,
            headers: { Location: basePath + pathname + "/" + url.search },
          });
        } else if (!trailingSlash && hasTrailing) {
          return new Response(null, {
            status: 308,
            headers: { Location: basePath + pathname.replace(/\/+$/, "") + url.search },
          });
        }
      }

      // Build a request with the basePath-stripped URL for middleware and
      // downstream handlers. In Workers the incoming request URL still
      // contains basePath; prod-server constructs its webRequest from
      // the already-stripped URL, so we replicate that here.
      if (basePath) {
        const strippedUrl = new URL(request.url);
        strippedUrl.pathname = pathname;
        request = new Request(strippedUrl, request);
      }

      // Build request context for has/missing condition matching.
      // Created before middleware runs, matching prod-server ordering.
      const reqCtx = requestContextFromRequest(request);

      // ── 3. Run middleware ──────────────────────────────────────────
      let resolvedUrl = urlWithQuery;
      const middlewareHeaders: Record<string, string> = {};
      let middlewareRewriteStatus: number | undefined;
      if (typeof runMiddleware === "function") {
        const result = await (runMiddleware as (req: Request) => Promise<{
          continue: boolean;
          redirectUrl?: string;
          redirectStatus?: number;
          response?: Response;
          responseHeaders?: Array<[string, string]>;
          rewriteUrl?: string;
          rewriteStatus?: number;
        }>)(request);

        if (!result.continue) {
          if (result.redirectUrl) {
            return new Response(null, {
              status: result.redirectStatus ?? 307,
              headers: { Location: result.redirectUrl },
            });
          }
          if (result.response) {
            return result.response;
          }
        }

        // Collect middleware response headers to merge into final response
        if (result.responseHeaders) {
          for (const [key, value] of result.responseHeaders) {
            middlewareHeaders[key] = value;
          }
        }

        // Apply middleware rewrite
        if (result.rewriteUrl) {
          resolvedUrl = result.rewriteUrl;
        }

        // Apply custom status code from middleware rewrite
        middlewareRewriteStatus = result.rewriteStatus;
      }

      // Unpack x-middleware-request-* headers into the actual request so
      // that renderPage / handleApiRoute see middleware-modified headers.
      // Workers incoming request headers are immutable, so clone if needed.
      const mwReqPrefix = "x-middleware-request-";
      const mwReqHeaders: Record<string, string> = {};
      for (const key of Object.keys(middlewareHeaders)) {
        if (key.startsWith(mwReqPrefix)) {
          const realName = key.slice(mwReqPrefix.length);
          mwReqHeaders[realName] = middlewareHeaders[key];
          delete middlewareHeaders[key];
        } else if (key.startsWith("x-middleware-")) {
          delete middlewareHeaders[key];
        }
      }
      if (Object.keys(mwReqHeaders).length > 0) {
        const newHeaders = new Headers(request.headers);
        for (const [k, v] of Object.entries(mwReqHeaders)) {
          newHeaders.set(k, v);
        }
        request = new Request(request.url, {
          method: request.method,
          headers: newHeaders,
          body: request.body,
          // @ts-expect-error -- duplex needed for streaming request bodies
          duplex: request.body ? "half" : undefined,
        });
      }

      let resolvedPathname = resolvedUrl.split("?")[0];

      // ── 4. Apply custom headers from next.config.js ───────────────
      if (configHeaders.length) {
        const matched = matchHeaders(resolvedPathname, configHeaders, reqCtx);
        for (const h of matched) {
          middlewareHeaders[h.key.toLowerCase()] = h.value;
        }
      }

      // ── 5. Apply redirects from next.config.js ────────────────────
      if (configRedirects.length) {
        const redirect = matchRedirect(resolvedPathname, configRedirects, reqCtx);
        if (redirect) {
          const dest = basePath && !redirect.destination.startsWith(basePath)
            ? basePath + redirect.destination
            : redirect.destination;
          return new Response(null, {
            status: redirect.permanent ? 308 : 307,
            headers: { Location: dest },
          });
        }
      }

      // ��─ 6. Apply beforeFiles rewrites from next.config.js ─────────
      if (configRewrites.beforeFiles?.length) {
        const rewritten = matchRewrite(resolvedPathname, configRewrites.beforeFiles, reqCtx);
        if (rewritten) {
          if (isExternalUrl(rewritten)) {
            return proxyExternalRequest(request, rewritten);
          }
          resolvedUrl = rewritten;
          resolvedPathname = rewritten.split("?")[0];
        }
      }

      // ── 7. API routes ─────────────────────────────────────────────
      if (resolvedPathname.startsWith("/api/") || resolvedPathname === "/api") {
        const response = typeof handleApiRoute === "function"
          ? await handleApiRoute(request, resolvedUrl)
          : new Response("404 - API route not found", { status: 404 });
        return mergeHeaders(response, middlewareHeaders, middlewareRewriteStatus);
      }

      // ── 8. Apply afterFiles rewrites from next.config.js ──────────
      if (configRewrites.afterFiles?.length) {
        const rewritten = matchRewrite(resolvedPathname, configRewrites.afterFiles, reqCtx);
        if (rewritten) {
          if (isExternalUrl(rewritten)) {
            return proxyExternalRequest(request, rewritten);
          }
          resolvedUrl = rewritten;
          resolvedPathname = rewritten.split("?")[0];
        }
      }

      // ── 9. Page routes ────────────────────────────────────────────
      let response: Response | undefined;
      if (typeof renderPage === "function") {
        response = await renderPage(request, resolvedUrl, null);

        // ── 10. Fallback rewrites (if SSR returned 404) ─────────────
        if (response && response.status === 404 && configRewrites.fallback?.length) {
          const fallbackRewrite = matchRewrite(resolvedPathname, configRewrites.fallback, reqCtx);
          if (fallbackRewrite) {
            if (isExternalUrl(fallbackRewrite)) {
              return proxyExternalRequest(request, fallbackRewrite);
            }
            response = await renderPage(request, fallbackRewrite, null);
          }
        }
      }

      if (!response) {
        return new Response("404 - Not found", { status: 404 });
      }

      return mergeHeaders(response, middlewareHeaders, middlewareRewriteStatus);
    } catch (error) {
      console.error("[vinext] Worker error:", error);
      return new Response("Internal Server Error", { status: 500 });
    }
  },
};

/**
 * Merge middleware/config headers into a response.
 * Response headers take precedence over middleware headers, matching
 * the behavior in prod-server.ts.
 */
function mergeHeaders(
  response: Response,
  extraHeaders: Record<string, string>,
  statusOverride?: number,
): Response {
  if (!Object.keys(extraHeaders).length && !statusOverride) return response;
  // Middleware/config headers go in first (lower precedence), then
  // response headers overlay them (higher precedence).
  const merged: Record<string, string> = { ...extraHeaders };
  response.headers.forEach((v, k) => { merged[k] = v; });
  return new Response(response.body, {
    status: statusOverride ?? response.status,
    statusText: response.statusText,
    headers: merged,
  });
}
